/**
 * semantic-release configuration.
 *
 * PUBLISHING (git tag → refs/tags/*, GitHub Release, SBOM) always runs on the
 * workflow's GITHUB_TOKEN. Tags are not branch-protected, so this needs no
 * special permission.
 *
 * COMMIT-BACK (bumping CHANGELOG.md / package.json / Chart.yaml on main via
 * @semantic-release/git) is OPT-IN and OFF by default. It pushes directly to
 * main, which branch protection rejects for GITHUB_TOKEN (GH006 — required
 * status checks can't be satisfied by a fresh commit). It self-activates when a
 * bypass-capable RELEASE_TOKEN secret exists: `.github/workflows/release.yml`
 * sets SEMANTIC_RELEASE_COMMIT_BACK=true and passes that token, so the push runs
 * as an admin (enforce_admins=false → bypasses the checks).
 *
 *   No RELEASE_TOKEN  → commit-back plugin omitted → publishing still works;
 *                       package.json / CHANGELOG / Chart.yaml stay frozen
 *                       in-repo (in-sync, so the helm-chart guard passes).
 *   RELEASE_TOKEN set → commit-back plugin included → versions advance in-repo
 *                       in lock-step, as before.
 *
 * See docs/implementation-notes/2026-07-11-release-drop-git-commitback.md.
 */
const commitBack = process.env.SEMANTIC_RELEASE_COMMIT_BACK === 'true';

const plugins = [
  [
    '@semantic-release/commit-analyzer',
    {
      preset: 'conventionalcommits',
      releaseRules: [
        { type: 'feat', release: 'minor' },
        { type: 'fix', release: 'patch' },
        { type: 'perf', release: 'patch' },
        { type: 'refactor', release: 'patch' },
        { type: 'revert', release: 'patch' },
        { breaking: true, release: 'major' },
      ],
    },
  ],
  [
    '@semantic-release/release-notes-generator',
    {
      preset: 'conventionalcommits',
      presetConfig: {
        types: [
          { type: 'feat', section: '✨ Features', hidden: false },
          { type: 'fix', section: '🐛 Bug Fixes', hidden: false },
          { type: 'perf', section: '⚡ Performance', hidden: false },
          { type: 'refactor', section: '♻️ Refactoring', hidden: false },
          { type: 'revert', section: '⏪ Reverted', hidden: false },
          { type: 'docs', section: '📚 Documentation', hidden: false },
          { type: 'chore', section: '🔧 Maintenance', hidden: true },
          { type: 'test', section: '✅ Tests', hidden: true },
          { type: 'ci', section: '🏗️ CI/CD', hidden: true },
          { type: 'build', section: '📦 Build', hidden: true },
          { type: 'style', section: '💄 Style', hidden: true },
        ],
      },
    },
  ],
  [
    '@semantic-release/changelog',
    {
      changelogFile: 'CHANGELOG.md',
      changelogTitle:
        '# Changelog\n\nAll notable changes to **inflect-compliance** are documented here.\nThis file is auto-generated by [semantic-release](https://github.com/semantic-release/semantic-release).',
    },
  ],
  ['@semantic-release/npm', { npmPublish: false }],
  [
    // Writes infra/helm/inflect/Chart.yaml::appVersion = the release version.
    // When commit-back is OFF this write is discarded (uncommitted); it is kept
    // so that enabling commit-back restores lock-step chart/version sync with no
    // other change. Script fails LOUDLY (non-zero exit) if the regex misses.
    '@semantic-release/exec',
    { prepareCmd: 'node scripts/sync-chart-version.mjs ${nextRelease.version}' },
  ],
];

// Commit the version bump back to main — ONLY when a bypass-capable token is
// wired in (see header). Omitted by default so GITHUB_TOKEN never trips GH006.
if (commitBack) {
  plugins.push([
    '@semantic-release/git',
    {
      assets: ['CHANGELOG.md', 'package.json', 'package-lock.json', 'infra/helm/inflect/Chart.yaml'],
      message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}',
    },
  ]);
}

plugins.push('@semantic-release/github');

module.exports = {
  branches: ['main'],
  tagFormat: 'v${version}',
  plugins,
};
