/**
 * Tier-1 ag workflow — agro-intel data streams.
 *
 * Regression-proofs the agronomic-telemetry surface that feeds the
 * spray-window / disease-risk signals: a per-field data stream is created
 * and its readings endpoint responds. (AgroSignal rows themselves are
 * generated by the background weather-pull job from these streams +
 * Open-Meteo, with no synchronous HTTP surface, so this spec exercises
 * the stream config + readings API — the operator-facing half.)
 *
 * API-only E2E (no agro UI page). Seeds a field via ag-fixtures.
 */
import { test, expect } from './fixtures';
import { createField } from './ag-fixtures';

test('agro intel: a field data stream is created and its readings endpoint responds', async ({ authedPage, isolatedTenant }) => {
    const slug = isolatedTenant.tenantSlug;
    const api = authedPage.request;

    const locationId = await createField(api, slug, 'North Farm');

    const res = await api.post(`/api/t/${slug}/agro/data-streams`, {
        data: { key: 'soil-1', name: 'Soil Moisture Probe 1', kind: 'SOIL_MOISTURE', unit: '%', locationId },
    });
    expect(res.status(), `create data stream: ${await res.text()}`).toBe(201);
    const stream = await res.json();
    expect(stream.id).toBeTruthy();

    // It appears in the field's stream list.
    const list = await (await api.get(`/api/t/${slug}/agro/data-streams`)).json();
    const arr = Array.isArray(list) ? list : list.items;
    expect(arr.some((s: { id: string }) => s.id === stream.id)).toBe(true);

    // The readings endpoint responds (empty until an ingest posts readings).
    const readings = await api.get(`/api/t/${slug}/agro/data-streams/${stream.id}/readings`);
    expect(readings.ok(), `readings: ${readings.status()}`).toBeTruthy();
    expect(Array.isArray(await readings.json())).toBe(true);
});
