#!/usr/bin/env tsx
/**
 * Index a tenant's own data into tenant-scoped RAG chunks (feat/ai-rag).
 *
 * Walks the tenant's:
 *   • LogEntry          (title + notes)          → sourceType JOURNAL
 *   • CropPlan          (name + notes)           → sourceType CROP_PLAN
 *   • Planting          (notes)                  → sourceType CROP_PLAN
 *   • Item              (name + sku label)       → sourceType LABEL
 *   • InventoryLot      (lot label)              → sourceType LABEL
 *   • published KnowledgeArticleVersion.contentText → sourceType KB
 *
 * into tenant-private KnowledgeChunks (tenantId = the tenant). All reads
 * + writes run inside `runInTenantContext`, so RLS isolates the tenant —
 * one tenant's index can never leak into another's. Embeddings are then
 * generated by `runEmbedChunks` (batched, also tenant-scoped).
 *
 * Idempotent on (tenantId, sourceType, sourceRef): a chunk already
 * present for a record is skipped, so a re-run only indexes new data.
 *
 * Usage:
 *   tsx scripts/rag/ingest-tenant.ts --tenant <slug>
 *   tsx scripts/rag/ingest-tenant.ts            # first tenant
 */
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import type { KnowledgeChunkSourceType } from '@prisma/client';
import { runInTenantContext } from '../../src/lib/db-context';
import { runEmbedChunks } from '../../src/app-layer/jobs/embed-chunks';
import type { RequestContext } from '../../src/app-layer/types';

interface PendingChunk {
    sourceType: KnowledgeChunkSourceType;
    source: string;
    sourceRef: string;
    text: string;
}

/** Strip HTML tags + collapse whitespace (KB content is TipTap HTML). */
function plainText(html: string): string {
    return html.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
}

function ctxFor(tenantId: string): RequestContext {
    return {
        userId: 'system:rag-ingest-tenant',
        tenantId,
        requestId: `rag-ingest-${tenantId}`,
        role: 'ADMIN',
        permissions: { canRead: true, canWrite: true, canAdmin: true, canAudit: false, canExport: false },
    } as unknown as RequestContext;
}

export interface IngestTenantResult {
    tenantId: string;
    created: number;
    skipped: number;
    embedded: number;
}

export async function ingestTenant(
    prisma: PrismaClient,
    opts: { tenantSlug?: string } = {},
): Promise<IngestTenantResult> {
    const tenant = opts.tenantSlug
        ? await prisma.tenant.findUnique({ where: { slug: opts.tenantSlug }, select: { id: true } })
        : await prisma.tenant.findFirst({ where: { deletedAt: null }, select: { id: true }, orderBy: { createdAt: 'asc' } });
    if (!tenant) throw new Error(`No tenant found${opts.tenantSlug ? ` for slug "${opts.tenantSlug}"` : ''}`);

    const ctx = ctxFor(tenant.id);

    const created = await runInTenantContext(ctx, async (db) => {
        const pending: PendingChunk[] = [];

        // ── LogEntry → JOURNAL ──
        const logs = await db.logEntry.findMany({
            where: { deletedAt: null },
            select: { id: true, title: true, notes: true },
            take: 5000,
        });
        for (const l of logs) {
            const text = [l.title, l.notes].filter(Boolean).join(' — ').trim();
            if (text) pending.push({ sourceType: 'JOURNAL', source: 'Field journal', sourceRef: l.id, text });
        }

        // ── CropPlan → CROP_PLAN ──
        const plans = await db.cropPlan.findMany({
            where: { deletedAt: null },
            select: { id: true, name: true, notes: true },
            take: 5000,
        });
        for (const p of plans) {
            const text = [p.name, p.notes].filter(Boolean).join(' — ').trim();
            if (text) pending.push({ sourceType: 'CROP_PLAN', source: 'Crop plan', sourceRef: p.id, text });
        }

        // ── Planting → CROP_PLAN ──
        const plantings = await db.planting.findMany({
            where: { deletedAt: null, notes: { not: null } },
            select: { id: true, notes: true },
            take: 5000,
        });
        for (const pl of plantings) {
            const text = (pl.notes ?? '').trim();
            if (text) pending.push({ sourceType: 'CROP_PLAN', source: 'Planting', sourceRef: pl.id, text });
        }

        // ── Item → LABEL ──
        const items = await db.item.findMany({
            where: { deletedAt: null },
            select: { id: true, name: true, category: true, sku: true },
            take: 5000,
        });
        for (const it of items) {
            const text = [it.name, `category: ${it.category}`, it.sku ? `SKU: ${it.sku}` : null]
                .filter(Boolean).join(', ').trim();
            if (text) pending.push({ sourceType: 'LABEL', source: 'Inventory item', sourceRef: it.id, text });
        }

        // ── InventoryLot → LABEL ──
        const lots = await db.inventoryLot.findMany({
            where: { deletedAt: null },
            select: { id: true, lotCode: true, item: { select: { name: true } } },
            take: 5000,
        });
        for (const lot of lots) {
            const text = `Lot ${lot.lotCode} of ${lot.item.name}`.trim();
            pending.push({ sourceType: 'LABEL', source: 'Inventory lot', sourceRef: lot.id, text });
        }

        // ── published KnowledgeArticleVersion → KB ──
        // Only the current (published) version of PUBLISHED articles.
        const articles = await db.knowledgeArticle.findMany({
            where: { deletedAt: null, status: 'PUBLISHED', currentVersionId: { not: null } },
            select: {
                id: true,
                title: true,
                currentVersion: { select: { id: true, contentText: true } },
            },
            take: 5000,
        });
        for (const a of articles) {
            const cv = a.currentVersion;
            if (!cv?.contentText) continue;
            const body = plainText(cv.contentText);
            const text = `${a.title}. ${body}`.trim();
            if (text) pending.push({ sourceType: 'KB', source: 'Knowledge base', sourceRef: a.id, text, });
        }

        // Idempotency — skip records already chunked (by sourceType+sourceRef).
        let createdCount = 0;
        for (const c of pending) {
            const exists = await db.knowledgeChunk.findFirst({
                where: { tenantId: tenant.id, sourceType: c.sourceType, sourceRef: c.sourceRef },
                select: { id: true },
            });
            if (exists) continue;
            await db.knowledgeChunk.create({
                data: {
                    tenantId: tenant.id,
                    source: c.source,
                    sourceType: c.sourceType,
                    sourceRef: c.sourceRef,
                    text: c.text,
                    chunkIndex: 0,
                },
            });
            createdCount++;
        }
        return { pending: pending.length, created: createdCount };
    });

    // Embed the freshly-created (NULL-embedding) chunks in bounded batches.
    let embedded = 0;
    // Drain until no more un-embedded chunks remain (each call is bounded).
    for (let i = 0; i < 100; i++) {
        const r = await runEmbedChunks({ tenantId: tenant.id, batchSize: 256 });
        embedded += r.embedded;
        if (r.scanned === 0) break;
    }

    return {
        tenantId: tenant.id,
        created: created.created,
        skipped: created.pending - created.created,
        embedded,
    };
}

async function main(): Promise<number> {
    const tenantIdx = process.argv.indexOf('--tenant');
    const tenantSlug = tenantIdx >= 0 ? process.argv[tenantIdx + 1] : undefined;
    const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
    const prisma = new PrismaClient({ adapter });
    try {
        const res = await ingestTenant(prisma, { tenantSlug });
        console.log(
            `RAG tenant index: tenant ${res.tenantId} — ${res.created} chunk(s) created, ` +
                `${res.skipped} already present, ${res.embedded} embedded.`,
        );
        return 0;
    } finally {
        await prisma.$disconnect();
    }
}

if (require.main === module) {
    main().then((code) => process.exit(code)).catch((err) => {
        console.error('RAG tenant ingestion failed:', err);
        process.exit(1);
    });
}
